apiVersion: v1
kind: Service
metadata:
  name: aws-dms-task-exporter
  labels:
    app: aws-dms-task-exporter
  {{- with .Values.podAnnotations }}
  annotations:
    {{- toYaml . | nindent 6 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    app: aws-dms-task-exporter