apiVersion: v1
kind: Service
metadata:
  name: aws-dms-task-exporter
  labels:
    app: aws-dms-task-exporter
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: aws-dms-task-exporter